spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=

cloud:
  aws:
    s3:
      bucket: walkingpuppy7
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(1VyT4LAZAXdxO6mlTb+YnPG3qF1eV+pLDGQrQob2y2M=)
      secretKey: ENC(x0OaCwvmnt0piS9U4XqlqrVydMQGyHWQpXgAWAuhaT8hTK9ZZJw48+D9eeClNgrS/qw4EsF4ceg=)
