name: hanghaetinder
run-name: Running
on:
  push:
    branches:
      - develop
      - 'develop/**'

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: hanghaetinders3
  AWS_CODE_DEPLOY_APPLICATION: hanghaetinder
  AWS_CODE_DEPLOY_GROUP: hanghaetinder-group

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v3
      with:
        ref: develop
    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    - name: Build the project
      run: ./gradlew clean build -x test
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload to S3
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/hanghaetinders3/$GITHUB_SHA.zip --source .
    - name: Deploy to EC2
      run: |
        aws deploy create-deployment \
        --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
        --s3-location bucket=$AWS_S3_BUCKET,key=$GITHUB_SHA.zip,bundleType=zip
