name: hanghaetinder  # Workflow의 이름

on:
  push:  # push 이벤트 트리거
    branches:
      - develop  # develop 브랜치 push에 반응
      - 'develop/**'  # develop 브랜치 하위 브랜치 push에 반응

env:
  AWS_REGION: ap-northeast-2  # AWS 지역 설정
  AWS_S3_BUCKET: hanghaetinders3  # S3 버킷 이름
  AWS_CODE_DEPLOY_APPLICATION: hanghaetinder  # CodeDeploy 애플리케이션 이름
  AWS_CODE_DEPLOY_GROUP: hanghaetinder-group  # CodeDeploy 배포 그룹 이름

jobs:
  build-with-gradle:  # 빌드 작업 정의
    runs-on: ubuntu-20.04  # Ubuntu 20.04 환경에서 실행

    steps:  # 작업 단계 정의
    - name: develop 브랜치로 이동  # develop 브랜치로 이동하는 단계
      uses: actions/checkout@v3  # GitHub Actions에서 제공하는 checkout 액션 사용
      with:
        ref: develop  # develop 브랜치를 체크아웃

    - name: JDK 17 설치  # JDK 17 설치 단계
      uses: actions/setup-java@v3  # GitHub Actions에서 제공하는 Java 설치 액션 사용
      with:
        java-version: '17'  # Java 17 사용
        distribution: 'zulu'  # Zulu JDK 사용

    - name: gradlew에 실행 권한 부여  # gradlew 파일에 실행 권한을 부여하는 단계
      run: chmod +x ./gradlew

    - name: jasypt key주입  # jasypt 암호화 키 주입 단계
      run: echo ${{secrets.JASYPT}} | base64 --decode >> ./src/main/resources/application-common.yml

    - name: View application-common.yml  # application-common.yml 파일 내용 확인 단계
      run: cat ./src/main/resources/application-common.yml

    - name: 프로젝트 빌드  # 프로젝트 빌드 단계
      run: ./gradlew clean build -x test

    - name: AWS credential 설정  # AWS 자격 증명 설정 단계
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: S3에 업로드
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://hanghaetinders3/$GITHUB_SHA.zip
    - name: EC2에 배포
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=$GITHUB_SHA.zip,bundleType=zip 
